# Generated by Django 5.0 on 2023-12-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodTruck",
            fields=[
                ("locationid", models.IntegerField(primary_key=True, serialize=False)),
                ("Applicant", models.TextField()),
                ("Address", models.TextField()),
                ("Latitude", models.FloatField()),
                ("Longitude", models.FloatField()),
            ],
        ),
    ]
